name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc3

      - name: Generate documentation
        run: |
          mkdir -p docs
          pdoc --html --output-dir docs server
          # Create index file
          cat > docs/index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>IP Chat Server Documentation</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  max-width: 800px;
                  margin: 0 auto;
                  padding: 20px;
                  line-height: 1.6;
                }
                h1 { color: #333; }
                a { color: #0366d6; }
                .module-list { margin-top: 20px; }
              </style>
            </head>
            <body>
              <h1>IP Chat Server Documentation</h1>
              <p>Welcome to the IP Chat Server documentation. This page provides links to the API documentation generated from the code.</p>
              
              <div class="module-list">
                <h2>Available Modules:</h2>
                <ul>
                  <li><a href="server/">Main Server Package</a></li>
                </ul>
              </div>
              
              <div class="info">
                <h2>Repository Information</h2>
                <p>This documentation is auto-generated from the source code using pdoc3.</p>
                <p>Last updated: \$(date)</p>
              </div>
            </body>
          </html>
          EOF
          
          # Move the html files to the root of docs directory
          mv docs/server/* docs/
          
          # Copy README if it exists
          if [ -f README.md ]; then
            cp README.md docs/
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
